routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->middleware('guest');

Route::get('/refresh_captcha', 'Auth\RegisterController@refreshCaptcha')->name('refresh');

Route::get('/passwordExpiration','Auth\PwdExpirationController@showPasswordExpirationForm');
Route::post('/passwordExpiration','Auth\PwdExpirationController@postPasswordExpiration')->name('passwordExpiration');

Route::get('/changePassword','HomeController@showChangePasswordForm');
Route::post('/changePassword','HomeController@changePassword')->name('changePassword');

Auth::routes(['verify' => true]);

Route::middleware(['auth' => 'verified'])->group(function () {

    Route::prefix('appointments')->group(function () {

        Route::get('/', 'AppointmentController@create')->name('appointments.create');
        Route::get('index', 'AppointmentController@index')->name('appointment.index');
        Route::get('create', 'AppointmentController@create')->name('appointments.create');
        Route::post('store', 'AppointmentController@store');
        Route::post('storeExisting', 'AppointmentController@storeExisting');
        Route::get('edit/{id}', 'AppointmentController@edit')->name('appointments.edit');
        Route::post('update/{id}', 'AppointmentController@update');
        Route::get('show/{id}', 'AppointmentController@show')->name('appointments.show');
        Route::get('screening/{id}', 'AppointmentController@screening')->name('appointments.screening');
        Route::post('status/{id}', 'AppointmentController@status')->name('appointments.status');

        Route::get('calendar', 'AppointmentController@calendar')->name('appointments.calendar');

        Route::get('eventList', 'AppointmentController@eventList')->name('appointments.eventList');
        Route::get('slots', 'AppointmentController@slots');
        Route::get('byDate', 'AppointmentController@appointmentsByDate');

        Route::get('showscreen/{id}', 'AppointmentController@showscreen')->name('appointments.showscreen');
        Route::get('showconsent/{id}', 'AppointmentController@showconsent')->name('appointments.showconsent');

        Route::get('showprescription/{id}/{referer}', 'PrescriptionController@showprescription')->name('appointments.showprescription');
        Route::get('prescriptionform/{id}/{referer}', 'PrescriptionController@prescriptionform')->name('appointments.prescriptionform');
        Route::post('prescriptionupdate/{id}/{referer}', 'PrescriptionController@prescriptionupdate');
        Route::get('createprescription/{referer}', 'PrescriptionController@createprescription')->name('appointments.createprescription');

        Route::get('patientrecord/{id}/{referer}', 'PatientRecordController@patientrecord')->name('appointments.patientrecord');
        Route::post('createpatientrecord/{referer}', 'PatientRecordController@createpatientrecord')->name('appointments.createpatientrecord');
        Route::get('showpatientrecord/{id}/{referer}', 'PatientRecordController@showpatientrecord')->name('appointments.showpatientrecord');
        Route::post('patientrecordupdate/{id}/{referer}', 'PatientRecordController@patientrecordupdate');

        Route::get('patienthistory/{id}/{referer}', 'PatientController@patienthistory')->name('appointments.patienthistory');
        Route::get('download/{id}', 'PatientController@download');
        
        Route::get('screeningform', function () {
            return view('appointments.screeningform');
        });

        Route::get('consentform', function () {
            return view('appointments.consentform');
        });

        Route::get('patients', 'PatientController@index')->name('appointments.patients');
        Route::get('search', 'PatientController@search')->name('appointments.search');

        Route::get('patientlist', 'AppointmentController@patientList')->name('appointments.patientlist');
        Route::get('patientdetail/{id}', 'AppointmentController@patientdetails')->name('appointments.patientdetail');

        Route::get('superuser', 'AppointmentController@superuser')->name('appointments.superuser');
        Route::post('updateUserRole', 'AppointmentController@updateUserRole');

    });
});

app/Appointment.php
<?php

namespace App;

use App\Events\AppointmentCreated;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Appointment extends Model
{
    use Notifiable;

    protected $dispatchesEvents = [
        'created' => AppointmentCreated::class
    ];

    public function patient()
    {
        return $this->belongsTo('App\Patient');
    }

    public function timeSlot()
    {
        return $this->belongsTo('App\TimeSlot');
    }
}

app/Patient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Patient extends Model
{
    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function screening()
    {
        return $this->hasOne(Screening::class);
    }

    public function consent()
    {
        return $this->hasOne(Consent::class);
    }

    public function prescription()
    {
        return $this->hasMany(Prescription::class);
    }

    public function appointment()
    {
        return $this->hasMany(Appointment::class);
    }

    public function patientRecord()
    {
        return $this->hasMany(PatientRecord::class);
    }
}

app/TimeSlot.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class TimeSlot extends Model
{
    public function getSlotDateAttribute($date)
    {
        return Carbon::createFromFormat('Y-m-d', $date)->format('Y-m-d');
    }

    public function getSlotTimeAttribute($date)
    {
        return Carbon::createFromFormat('H:i:s', $date)->format('h:i A');
    }
}

app/Http/Controllers/AppointmentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CalendarEvent;
use App\Http\Requests\CalendarTimeSlot;
use App\Http\Requests\StoreAppointment;
use App\Http\Resources\CalendarEvents;
use App\Repositories\AppointmentRepositoryInterface;
use App\Repositories\PatientRepositoryInterface;
use App\Repositories\TimeSlotRepositoryInterface;
use App\Repositories\ScreeningRepositoryInterface;
use App\Repositories\ConsentRepositoryInterface;
use App\Repositories\PrescriptionRepositoryInterface;
use App\Repositories\PatientRecordRepositoryInterface;
use App\Repositories\DoctorRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\PostsExport;
use App\User;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
use DateTime;
use DatePeriod;
use DateInterval;

class AppointmentController extends Controller
{
    /**
     * @var \App\Repositories\AppointmentRepositoryInterface
     */
    private $appointmentRepository;
    private $doctorRepository;

    /**
     * @var \App\Repositories\PatientRepositoryInterface
     */
    private $patientRepository;

    private $timeSlotRepository;

    private $screeningRepository;

    private $consentRepository;

    private $prescriptionRepository;

    private $patientRecordRepository;


    public function __construct(
        AppointmentRepositoryInterface $appointmentRepository,
        PatientRepositoryInterface $patientRepository,
        TimeSlotRepositoryInterface $timeSlotRepository,
        ScreeningRepositoryInterface $screeningRepository,
        ConsentRepositoryInterface $consentRepository,
        PrescriptionRepositoryInterface $prescriptionRepository,
        PatientRecordRepositoryInterface $patientRecordRepository,
        DoctorRepositoryInterface $doctorRepository
    )
    {
        $this->appointmentRepository = $appointmentRepository;
        $this->patientRepository = $patientRepository;
        $this->timeSlotRepository = $timeSlotRepository;
        $this->screeningRepository = $screeningRepository;
        $this->consentRepository = $consentRepository;
        $this->prescriptionRepository = $prescriptionRepository;
        $this->patientRecordRepository = $patientRecordRepository;
        $this->doctorRepository = $doctorRepository;
    }

    /**
     * @return mixed
     */
    public function index(Request $request)
    {
        $page = 'My Appointments';
        if (auth()->user()->is_admin || auth()->user()->isSuperUser()) {
            $value = $request->get('filter');
            if ($value) {
                switch($value)
                {
                    case '8': {
                        $appointments = $this->appointmentRepository->getAll();
                        break;
                    }
                    case '1': {
                        $status = 'For Confirmation';
                        $appointments = $this->appointmentRepository->filterByStatus($status);
                        break;
                    }
                    case '2': {
                        $status = 'Confirmed';
                        $appointments = $this->appointmentRepository->filterByStatus($status);
                        break;
                    }
                    case '3': {
                        $status = 'Checked-In';
                        $appointments = $this->appointmentRepository->filterByStatus($status);
                        break;
                    }
                    case '4': {
                        $status = 'In-Chair';
                        $appointments = $this->appointmentRepository->filterByStatus($status);
                        break;
                    }
                    case '5': {
                        $status = 'Completed';
                        $appointments = $this->appointmentRepository->filterByStatus($status);
                        break;
                    }
                    case '6': {
                        $status = 'Cancelled';
                        $appointments = $this->appointmentRepository->filterByStatus($status);
                        break;
                    }
                    case '7': {
                        $status = 'Today';
                        $appointments = $this->appointmentRepository->filterByStatus($status);
                        break;
                    }
                }
            } else {
                $appointments = $this->appointmentRepository->getAllCurrent();
            }
        } else {
            $appointments = $this->appointmentRepository->getByUserId(auth()->user()->id);
        }

        switch($request->input('action'))
        {
            case 'EXCEL': {
                return Excel::download(new PostsExport, 'appointments.xlsx');
            }
            case 'CSV': {
                return Excel::download(new PostsExport, 'appointments.csv');
            }
        }

        return view('appointments.index', compact('appointments', 'page'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Request $request)
    {
        $page = 'Book an Appointment';

        $id = $request->get('id');
        $date = $request->get('date-slot', '');
        $time = $request->get('time-slot', '');
        $action = $request->get('action');
        $screeningFormData = [];
        $consentFormData = [];

        // if $id is null, no patient record yet, save form data to session
        if (is_null($id))
        {
            if ($action == "saveScreeningForm") {
                $request->validate([
                    'q1' => 'required',
                    'q2' => 'required',
                    'q3' => 'required',
                    'q4' => 'required',
                    'q5' => 'required',
                    'q6' => 'required',
                    'q7' => 'required',
                    'q8' => 'required',
                    'q9' => 'required',
                ]);
                $screeningFormData = $request->all();
                Session::put('screeningFormData', $screeningFormData);
                Session()->save();
            }

            if ($action == "saveConsentForm") {
                $consentFormData = $request->all();
                Session::put('consentFormData', $consentFormData);
                Session()->save();
            }

            if (!$date) {
                $date = now()->format('Y-m-d');
            }

            return view('appointments.create', compact('date', 'time', 'page'));
        }
        else
        {
            // $id is not null. Save form data to database.
            
            if ($action == "saveScreeningForm") {
                $request->validate([
                    'q1' => 'required',
                    'q2' => 'required',
                    'q3' => 'required',
                    'q4' => 'required',
                    'q5' => 'required',
                    'q6' => 'required',
                    'q7' => 'required',
                    'q8' => 'required',
                    'q9' => 'required',
                ]);
                $screeningFormData = $request->only([
                    'q1',
                    'q2',
                    'q3',
                    'q4',
                    'q5',
                    'q6',
                    'q7',
                    'q8',
                    'q9',
                    'body_temperature',
                    'q1_country',
                    'q2_country',
                    'q7_country',
                ]);
                $q = 0;
                $q |= number_format($screeningFormData['q1']);
                $q |= number_format($screeningFormData['q2']);
                $q |= number_format($screeningFormData['q3']);
                $q |= number_format($screeningFormData['q4']);
                $q |= number_format($screeningFormData['q5']);
                $q |= number_format($screeningFormData['q6']);
                $q |= number_format($screeningFormData['q7']);
                $q |= number_format($screeningFormData['q8']);
                $q |= number_format($screeningFormData['q9']);

                $screening = [];
                $screening['questions'] = $q;
                if (array_key_exists('q1_country', $screeningFormData)) {
                    $screening['q1_country'] = $screeningFormData['q1_country'];
                }
                if (array_key_exists('q2_country', $screeningFormData)) {
                    $screening['q2_country'] = $screeningFormData['q2_country'];
                }
                if (array_key_exists('q7_country', $screeningFormData)) {
                    $screening['q7_country'] = $screeningFormData['q2_country'];
                }
                $screening['body_temperature'] = $screeningFormData['body_temperature'];
                $screening['patient_id'] = $request->get('id');
                $screening = $this->screeningRepository->add($screening);

                if (auth()->user()->is_admin || auth()->user()->isSuperUser()) {
                    $appointments = $this->appointmentRepository->getAll();
                } else {
                    $appointments = $this->appointmentRepository->getByUserId(auth()->user()->id);
                }
                $page = 'My Appointments';
                $request->session()->flash('message', 'Screening Form added successfully.');
                return view('appointments.index', compact('appointments', 'page'));
            }
        }
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $page = 'Edit an Appointment';

        $appointment = $this->appointmentRepository->getById($id);

        return view('appointments.edit', compact('appointment', 'page'));
    }

    /**
     * @param \App\Http\Requests\StoreAppointment $request
     * @return mixed
     */

resources/views/appointments/patientlist.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card table-with-links">
                        <div class="card-body table-responsive">
                            @if ($errors->any())
                            <ul> 
                                @foreach ($errors->all() as $message)
                                    <li> {{ $message }}</li>
                                @endforeach
                            </ul>
                            @endif
                            {{--<form method="GET" action="{{ url('appointments/create') }}">--}}
                                {{--@csrf--}}
                            @if($patients->count() > 0)
                            
                                To book as an existing Patient, please select and click on the Patient list below:
                                <p></p>
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr class="success">
                                            <th class="text-left">Fullname</th>
                                            <th class="text-left">Contact Number</th>
                                            <th class="text-left">Email</th>
                                            <th class="text-left">Birthday</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($patients as $patient)
                                        <tr class="patient-row" data-href="{{ url ('appointments/patientdetail', ['id' => $patient->id]) }}">
                                            <td class="text-left">&nbsp;&nbsp;{{ $patient->full_name }} </td>
                                            <td class="text-left">&nbsp;&nbsp;{{ $patient->contact_number }} </td>
                                            <td class="text-left">&nbsp;&nbsp;{{ $patient->email }} </td>
                                            <td class="text-left">&nbsp;&nbsp;{{  date('M-d-Y', strtotime($patient->birthday)) }} </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                    <!-- @if ($patientsCount < 2 && $patientsCount > 0)
                                        <p><strong>{{ $patientsCount }} record found.</strong></p>
                                    @else
                                        <p><strong>{{ $patientsCount }} records found.</strong></p>
                                    @endif -->
                            @else
                                Is this your first time to book an appointment?
                            @endif
                                <p>Click <a href="{{ url('appointments/create') }}"><strong>HERE</strong></a> to book as a new Patient.</p>
                            {{--</form>--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('stylesheets')
    <style>
        .patient-row {
            cursor: pointer;
        }

    </style>
@endsection


@section('javascript')
    <script type="text/javascript">

    document.addEventListener("DOMContentLoaded", () => {
        const rows = document.querySelectorAll("tr[data-href]");

        rows.forEach(row => {
            row.addEventListener("click", () => {
                window.location.href = row.dataset.href;
            });
        });

        sessionStorage.removeItem('UVWXYZ');
        sessionStorage.removeItem('PQRST');
        sessionStorage.removeItem('KLMNO');
        sessionStorage.removeItem('FGHIJ');
        sessionStorage.removeItem('ABCDE');

        sessionStorage.removeItem('bdate');
    });
    </script>
@endsection

resources/views/appointments/show.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if(session()->has('message'))
                        <div class="alert alert-success">
                            <button type="button" aria-hidden="true" class="close" data-dismiss="alert">
                                <i class="nc-icon nc-simple-remove"></i>
                            </button>
                            <span>
                                <b>
                                    {{ session('message') }}
                                </b>
                            </span>
                        </div>
                    @endif
                    <div class="card stacked-form">
                        <div class="card-header ">
                            <h4 class="card-title">Appointment Details</h4>
                        </div>
                        <div class="card-body ">
                            <form>
                                <?php
                                    $var = [];
                                    $medHistory = [];

                                    if (!empty($appointment->patient->screening)) {
                                        if (($appointment->patient->screening->questions&1) == 1) {
                                            $var['#1'] = 'Yes';
                                        }
                                        if (($appointment->patient->screening->questions&2) == 2) {
                                            $var['#2'] = 'Yes';
                                        }
                                        if (($appointment->patient->screening->questions&4) == 4) {
                                            $var['#3'] = 'Yes';
                                        }
                                        if (($appointment->patient->screening->questions&8) == 8) {
                                            $var['#4'] = 'Yes';
                                        }
                                        if (($appointment->patient->screening->questions&16) == 16) {
                                            $var['#5'] = 'Yes';
                                        }
                                        if (($appointment->patient->screening->questions&32) == 32) {
                                            $var['#6'] = 'Yes';
                                        }
                                        if (($appointment->patient->screening->questions&64) == 64) {
                                            $var['#7'] = 'Yes';
                                        }
                                        if (($appointment->patient->screening->questions&128) == 128) {
                                            $var['#8'] = 'Yes';
                                        }
                                        if (($appointment->patient->screening->questions&256) == 256) {
                                            $var['#9'] = 'Yes';
                                        }

                                        $var = json_encode($var);
                                        $myJsonString = str_replace(['{', '}', '"'], '', $var);
                                        $finalString = str_replace(':', ' - ', $myJsonString);
                                        $finalString = str_replace(',', ',  ', $finalString);
                                    }

                                    if (($appointment->patient->medical_history&1) == 1) {
                                        array_push($medHistory,"Diabetes");
                                    }
                                    if (($appointment->patient->medical_history&2) == 2) {
                                        array_push($medHistory,"Bleeding Tendency");
                                    }
                                    if (($appointment->patient->medical_history&4) == 4) {
                                        array_push($medHistory,"Drug Sensitivity");
                                    }
                                    if (($appointment->patient->medical_history&8) == 8) {
                                        array_push($medHistory,"Heart Condition");
                                    }
                                    if (($appointment->patient->medical_history&16) == 16) {
                                        array_push($medHistory,"Rheumatic Fever");
                                    }
                                    if (($appointment->patient->medical_history&32) == 32) {
                                        array_push($medHistory,"Blood Pressure");
                                    }

                                    if (($appointment->patient->medical_history_others) != '') {
                                        $others = $appointment->patient->medical_history_others;
                                        array_push($medHistory, $others);
                                    }

                                    $medHistory = json_encode($medHistory);
                                    $medHis = str_replace(['[', ']', '"'], '', $medHistory);

                                ?>
                                <div class="form-group row">
                                    <label for="patient" class="col-sm-2 col-form-label">Patient Name</label>
                                    <div class="col-sm-10">
                                        <span>{{ $appointment->patient->full_name }}</span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="date" class="col-sm-2 col-form-label">Date</label>
                                    <div class="col-sm-10">
                                        <span>{{ $appointment->timeSlot->slot_date }}</span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="time" class="col-sm-2 col-form-label">Time</label>
                                    <div class="col-sm-10">
                                        <span>{{ $appointment->timeSlot->slot_time }}</span>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="time" class="col-sm-2 col-form-label">Contact Number</label>
                                    <div class="col-sm-10">
                                        <p>
                                            <span>{{ $appointment->patient->contact_number }}</span>
                                        </p>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="time" class="col-sm-2 col-form-label">reason/purpose of visit/consultation</label>
                                    <div class="col-sm-10">
                                        <p>
                                            <span>{{ $appointment->requirements }}</span>
                                        </p>
                                    </div>
                                </div>
                                @if(auth()->user()->isAdministrator())
                                <div class="form-group row">
                                    <label for="time" class="col-sm-2 col-form-label">Medical History</label>
                                    <div class="col-sm-10">
                                        <p>
                                            <span>{{ $medHis }}</span>
                                        </p>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label for="time" class="col-sm-2 col-form-label">Medicine Taken</label>
                                    <div class="col-sm-10">
                                        <p>
                                            <span>{{ $appointment->patient->med_name == ',,' ?  '' : $appointment->patient->med_name }}</span>
                                        </p>
                                    </div>
                                </div>
                                @endif
                                <div class="form-group row">
                                    <label for="time" class="col-sm-2 col-form-label">Status</label>
                                    <div class="col-sm-10">
                                        <p>
                                            <span>{{ $appointment->status }}</span>
                                        </p>
                                    </div>
                                </div>
                                @if($appointment->patient->image)
                                <div class="form-group row">
                                    <label for="time" class="col-sm-2 col-form-label">Uploaded Image</label>
                                    <div class="col-sm-10">
                                        <a href="{{ url('appointments/download', ['id' => $appointment->patient->id]) }}">{{ $appointment->patient->image }} </a>
                                    </div>
                                </div>
                                @endif
                            </form>
                        </div>
                        <div class="card-footer ">
                            <a href="{{ url('appointments/edit', ['id' => $appointment->id]) }}" class="btn btn-fill btn-primary" rel="tooltip" title="Edit Appointment">Edit</a>
                            <a href="{{ url('appointments/showscreen', ['id' => $appointment->id]) }}" class="btn btn-fill btn-primary" rel="tooltip" title="View/Edit COVID-19 Screening Form">Edit Screening Form</a>
                            {{--<a href="{{ url('appointments/showconsent', ['id' => $appointment->id]) }}" class="btn btn-fill btn-primary" rel="tooltip" title="View/Edit COVID-19 Dental Consent Form">Consent</a>--}}
                            <a href="{{ url('appointments/index') }}" class="btn btn-fill btn-default">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection